on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: Build

jobs:
  linting:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install Dev dependencies
        run: |
          pip install pytest black mypy pytest-asyncio pytest-cov pytest-black pytest-mypy
          pip install -e .
      - name: Run Tests
        run: python setup.py test
      - uses: codecov/codecov-action@v1
        with:
          file: ./reports/coverage.xml 
          flags: unittests 
          fail_ci_if_error: true 
          verbose: true 
          

