on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: Build

jobs:
  linting:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install Dev dependencies
        run: |
          pip install pytest blackmypy pytest-asynciopy test-cov pytest-black pytest-mypy
          pip install -e .
      - name: Run Tests
        run: python setup.py test
      - name: Check coverage
        run: codecov

